# Generated by Django 5.1 on 2024-11-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('cliente_a', models.CharField(max_length=100)),
                ('vehiculo_v', models.CharField(max_length=100)),
                ('precio_f', models.BigIntegerField()),
                ('metodo_p', models.CharField(max_length=100)),
            ],
        ),
    ]
