# Generated by Django 5.1 on 2024-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.BigIntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('fecha_n', models.DateTimeField()),
                ('historial_c', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=100)),
            ],
        ),
    ]
