# Generated by Django 5.1.3 on 2024-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año', models.SmallIntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('kilometraje', models.SmallIntegerField()),
            ],
        ),
    ]
