# Generated by Django 5.1 on 2024-11-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.SmallIntegerField()),
                ('turno', models.BigIntegerField()),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
    ]
